import streamlit as st

STRINGS = {
    "ar": {
        "LANG_SELECT": "اللغة / Language",
        "APP_TITLE": "نظام رصد الحشود الذكي",
        "SIDEBAR_HEADER": "📌 لوحة التحكم",
        "RUN_SYSTEM": "🚀 تشغيل النظام (مستمر)",
        "MENU_LABEL": "القائمة:",

        # القوائم
        "TAB_LIVE": "البث المباشر",
        "TAB_DASHBOARD": "لوحة التحليل",
        "TAB_REPORTS": "التقارير",
        "TAB_SETTINGS": "الإعدادات",

        # تسجيل الدخول
        "LOGIN_TITLE": "تسجيل الدخول للنظام الأمني",
        "USER_LABEL": "اسم المستخدم",
        "PASS_LABEL": "كلمة المرور",
        "LOGIN_BTN": "دخول",
        "AUTH_SUCCESS": "تم تسجيل الدخول بنجاح!",
        "AUTH_FAIL": "بيانات الدخول غير صحيحة",

        # Live Feed
        "NUM_CAMS": "عدد الكاميرات",
        "CAM_EXPANDER": "📷 إعدادات كاميرا",
        "NAME": "الاسم",
        "SOURCE": "المصدر",
        "CAM_ID": "رقم الكاميرا",
        "URL": "الرابط (RTSP/URL)",
        "FILE": "اختر فيديو",
        "MANUAL_FILE": "أو مسار الملف",
        "HEIGHT": "الارتفاع (Y)",
        "ANGLE": "الدوران",
        "WIDTH": "العرض",
        "FLIP": "عكس الاتجاه",
        "LIVE_TITLE": "🖥️ غرفة المراقبة الحية",
        "WAITING": "⏳ بانتظار إشارة",
        "SYSTEM_OFF": "⚠️ النظام متوقف",
        "IN": "دخول",
        "OUT": "خروج",
        "ENTRY_SIDE": "جهة الدخول",

        # Dashboard (الداشبورد)
        "DASH_TITLE": "مركز الاستخبارات والتحليل",
        "NO_DATA": "لا توجد بيانات مسجلة حالياً.",
        "SUMMARY_TITLE": "📍 ملخص حركة اليوم",
        "TOTAL_VISITORS": "👥 زوار اليوم",
        "CURRENT_OCCUPANTS": "🏠 المتواجدون الآن",
        "OCCUPANCY_RATE": "💯 نسبة الإشغال",
        "AVG_STAY": "⏱️ متوسط البقاء",
        "LIVE_GATES": "🚪 حالة المداخل الحية",
        "FLOW_CHART": "📈 تحليل التدفق بالساعة",
        "GAUGE_CHART": "🎯 مؤشر الامتلاء",
        "PEAK_CHART": "🕒 أوقات الذروة",
        "RECENT_LOGS": "📄 سجل العمليات الأخيرة",
        "DANGER": "❌ خطر: تجاوز السعة ({0}%)",
        "WARNING": "🚨 تحذير: ازدحام ({0}%)",
        "NORMAL": "✅ حالة مستقرة ({0}%)",
        "DETAILED_ANALYSIS": "🔍 تحليل تفصيلي لكل مدخل",
        "SELECT_CAM": "🎯 اختر الكاميرا:",
        "CAM_IN": "دخول المدخل",
        "CAM_OUT": "خروج المدخل",
        "NET_MOVE": "صافي الحركة",
        "CAM_ACTIVITY": "نشاط {0} خلال اليوم",
        "AXIS_HOUR": "الساعة",
        "AXIS_COUNT": "العدد",
        "AXIS_TYPE": "النوع",

        # Reports (التقارير)
        "REPORTS_TITLE": "📑 السجلات والتقارير",
        "HISTORY_HEADER": "🗓️ السجل التاريخي المجمع",
        "BTN_UPDATE_HISTORY": "💾 ترحيل بيانات اليوم للسجل",
        "MSG_HISTORY_UPDATED": "تم تحديث السجل التاريخي بنجاح!",
        "NO_HISTORY": "لا يوجد سجلات تاريخية.",
        "DETAILS_HEADER": "🔍 تفاصيل الحركات (Raw Data)",
        "BTN_EXPORT": "📥 تحميل التقرير (CSV)",
        "FILTER_DATE": "📅 فلتر بالتاريخ:",
        "NO_DETAILS_DATE": "لا توجد سجلات لهذا التاريخ.",

        # Settings
        "SET_TITLE": "⚙️ إعدادات النظام",
        "SET_PARAMS": "🛠️ ضبط المعايير",
        "SET_CAP": "الحد الأقصى للاستيعاب",
        "SET_CONF": "دقة الذكاء الاصطناعي",
        "DANGER_ZONE": "⚠️ منطقة الخطر",
        "RESET_BTN": "🔄 تصفير العدادات (Factory Reset)",
        "RESET_MSG": "تم تصفير العدادات بنجاح!"
    },
    "en": {
        "LANG_SELECT": "Language / اللغة",
        "APP_TITLE": "Smart Crowd Analytics",
        "SIDEBAR_HEADER": "📌 Control Panel",
        "RUN_SYSTEM": "🚀 Run System",
        "MENU_LABEL": "Menu:",

        "TAB_LIVE": "Live Feed",
        "TAB_DASHBOARD": "Dashboard",
        "TAB_REPORTS": "Reports",
        "TAB_SETTINGS": "Settings",

        "LOGIN_TITLE": "Security System Login",
        "USER_LABEL": "Username",
        "PASS_LABEL": "Password",
        "LOGIN_BTN": "Login",
        "AUTH_SUCCESS": "Login Successful!",
        "AUTH_FAIL": "Invalid Credentials",

        "NUM_CAMS": "Number of Cameras",
        "CAM_EXPANDER": "📷 Camera Settings",
        "NAME": "Name",
        "SOURCE": "Source",
        "CAM_ID": "Camera ID",
        "URL": "URL (RTSP)",
        "FILE": "Select Video",
        "MANUAL_FILE": "Or File Path",
        "HEIGHT": "Height (Y)",
        "ANGLE": "Angle",
        "WIDTH": "Width",
        "FLIP": "Flip Dir",
        "LIVE_TITLE": "🖥️ Live Monitoring Room",
        "WAITING": "⏳ Waiting...",
        "SYSTEM_OFF": "⚠️ System Stopped",
        "IN": "IN",
        "OUT": "OUT",
        "ENTRY_SIDE": "Entry Side",

        "DASH_TITLE": "Intelligence & Analytics Center",
        "NO_DATA": "No Data Available.",
        "SUMMARY_TITLE": "📍 Daily Summary",
        "TOTAL_VISITORS": "👥 Total Visitors",
        "CURRENT_OCCUPANTS": "🏠 Current Occupants",
        "OCCUPANCY_RATE": "💯 Occupancy Rate",
        "AVG_STAY": "⏱️ Avg Stay",
        "LIVE_GATES": "🚪 Live Gates Status",
        "FLOW_CHART": "📈 Hourly Flow Analysis",
        "GAUGE_CHART": "🎯 Occupancy Gauge",
        "PEAK_CHART": "🕒 Peak Hours",
        "RECENT_LOGS": "📄 Recent Logs",
        "DANGER": "❌ DANGER: Over Capacity ({0}%)",
        "WARNING": "🚨 WARNING: High Traffic ({0}%)",
        "NORMAL": "✅ Stable Status ({0}%)",
        "DETAILED_ANALYSIS": "🔍 Detailed Entry Analysis",
        "SELECT_CAM": "🎯 Select Camera:",
        "CAM_IN": "Entry IN",
        "CAM_OUT": "Entry OUT",
        "NET_MOVE": "Net Movement",
        "CAM_ACTIVITY": "Activity for {0}",
        "AXIS_HOUR": "Hour",
        "AXIS_COUNT": "Count",
        "AXIS_TYPE": "Type",

        "REPORTS_TITLE": "📑 Logs & Reports",
        "HISTORY_HEADER": "🗓️ Historical Summary",
        "BTN_UPDATE_HISTORY": "💾 Archive Today's Data",
        "MSG_HISTORY_UPDATED": "History Updated Successfully!",
        "NO_HISTORY": "No history logs found.",
        "DETAILS_HEADER": "🔍 Detailed Movements",
        "BTN_EXPORT": "📥 Export Report (CSV)",
        "FILTER_DATE": "📅 Filter by Date:",
        "NO_DETAILS_DATE": "No records for this date.",

        "SET_TITLE": "⚙️ System Settings",
        "SET_PARAMS": "🛠️ Parameters",
        "SET_CAP": "Max Capacity",
        "SET_CONF": "AI Confidence",
        "DANGER_ZONE": "⚠️ Danger Zone",
        "RESET_BTN": "🔄 Factory Reset",
        "RESET_MSG": "Reset Successful!"
    }
}

def get(key):
    lang = st.session_state.get('language', 'ar')
    return STRINGS[lang].get(key, key)